# Generated by Django 5.1.2 on 2024-10-31 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_consume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='food_consumed',
        ),
        migrations.AddField(
            model_name='consume',
            name='food_consumed',
            field=models.ManyToManyField(to='mysite.food'),
        ),
    ]
