# Generated by Django 5.1.2 on 2024-10-31 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_remove_consume_food_consumed_consume_food_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='food_consumed',
        ),
        migrations.AddField(
            model_name='consume',
            name='food_consumed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mysite.food'),
        ),
    ]
