# Generated by Django 5.1.2 on 2024-11-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_alter_consume_food_consumed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='food_consumed',
        ),
        migrations.AddField(
            model_name='consume',
            name='food_consumed',
            field=models.ManyToManyField(to='mysite.food'),
        ),
    ]
