# Generated by Django 5.1.2 on 2024-11-01 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_remove_consume_food_consumed_consume_food_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='consume',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
