# Generated by Django 5.1.2 on 2024-11-01 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_consume_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consume',
            name='food_consumed',
        ),
        migrations.AddField(
            model_name='consume',
            name='food_consumed',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='mysite.food'),
        ),
    ]
