# Generated by Django 5.1.2 on 2025-01-02 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_consume_food_consumed_consume_food_consumed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='consume',
            name='food_consumed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.food'),
        ),
        migrations.AlterField(
            model_name='consume',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
